---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Apply
  labels:
    app: Apply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Apply
  template:
    metadata:
      labels:
        app: Apply
    spec:
      containers:
        - name: Apply
          image: username/Apply:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Pay
  labels:
    app: Pay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Pay
  template:
    metadata:
      labels:
        app: Pay
    spec:
      containers:
        - name: Pay
          image: username/Pay:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Delivery
  template:
    metadata:
      labels:
        app: Delivery
    spec:
      containers:
        - name: Delivery
          image: username/Delivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyPage
  labels:
    app: MyPage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyPage
  template:
    metadata:
      labels:
        app: MyPage
    spec:
      containers:
        - name: MyPage
          image: username/MyPage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Apply
  labels:
    app: Apply
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Apply


---


apiVersion: v1
kind: Service
metadata:
  name: Pay
  labels:
    app: Pay
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Pay


---


apiVersion: v1
kind: Service
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Delivery


---


apiVersion: v1
kind: Service
metadata:
  name: MyPage
  labels:
    app: MyPage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: MyPage

